<?php

namespace CG_TMP_PROJECTNAME\App\Model;


/**
 * Description of CG_TMP_Object
 * Generated by CoreGenerator
 * 
 * @author kminekmatej, CG_TMP_DATE
 */
class CG_TMP_Object extends CG_TMP_EXTENDS_OBJECT {

    /*CG_TMP_FIELD:START*/
    /** @var CG_TMP_FIELD_TYPE */
    private $CG_TMP_FIELD_NAME;
    /*CG_TMP_FIELD:END*/

    /*CG_TMP_GETTER:START*/
    public function getCG_TMP_FIELD_UC() {
        return $this->CG_TMP_FIELD_NAME;
    }
    /*CG_TMP_GETTER:END*/

    /*CG_TMP_SETTER:START*/
    /** @return CG_TMP_Object */
    public function setCG_TMP_FIELD_UC(CG_TMP_FIELD_TYPE $CG_TMP_FIELD) {
        $this->CG_TMP_FIELD_NAME = $CG_TMP_FIELD;
        return $this;
    }
    /*CG_TMP_SETTER:END*/

}
