<?php

namespace CG_TMP_PROJECTNAME\App\Model;

/**
 * Description of CreatedByObject
 * Generated by CoreGenerator
 * 
 * @author kminekmatej, CG_TMP_DATE
 */
class CreatedByObject extends IdObject{
    
    /** @var string */
    private $createdBy;
    
    function getCreatedBy() {
        return $this->createdBy;
    }

    function setCreatedBy($createdBy) {
        $this->createdBy = $createdBy;
        return $this;
    }

    
}
