<?php

namespace CG_TMP_PROJECTNAME\App\Model;

use DateTime;

/**
 * Description of IdObject
 * Generated by CoreGenerator
 * 
 * @author kminekmatej, CG_TMP_DATE
 */
class IdObject {
    
    /** @var int */
    private $id;
    
    /** @var DateTime */
    private $created;
    
    
    public function getId() {
        return $this->id;
    }

    public function setId($id) {
        $this->id = $id;
        return $this;
    }
    
    function getCreated() {
        return $this->created;
    }

    function setCreated(DateTime $created) {
        $this->created = $created;
        return $this;
    }


}
